In [1]:
import tensorflow as tf
import tensorlayer as tl

In [2]:
tf.reset_default_graph()

In [3]:
tl.layers.set_name_reuse(enable=True)

In [4]:
g = tf.Graph()
g.as_default()

In [5]:
x = tf.placeholder(tf.float32, [None, 2]) # 입력 데이터
network = tl.layers.InputLayer(x) # 입력층
network = tl.layers.DenseLayer(network, n_units=1, act=tf.sigmoid, name="output") # 출력층

  tensorlayer:Instantiate InputLayer  input_layer: (?, 2)
  tensorlayer:Instantiate DenseLayer  output: 1, sigmoid


In [7]:
predict = network.outputs # 예측값
y = tf.placeholder(tf.float32, [None, 1]) # 실제 값
cost = tl.cost.binary_cross_entropy(predict, y)

In [8]:
import numpy
xdata = numpy.array([[0, 0], [1, 0], [0, 1], [1, 1]])
ydata = numpy.array([0, 0, 0, 1]).reshape((4, 1))
data = {x: xdata, y: ydata}

In [9]:
data

{<tf.Tensor 'Placeholder:0' shape=(?, 2) dtype=float32>: array([[0, 0],
        [1, 0],
        [0, 1],
        [1, 1]]),
 <tf.Tensor 'Placeholder_2:0' shape=(?, 1) dtype=float32>: array([[0],
        [0],
        [0],
        [1]])}

In [10]:
gd = tf.train.GradientDescentOptimizer(learning_rate=1)
train_step = gd.minimize(cost)  # cost를 최소화한다

In [11]:
session = tf.InteractiveSession()
session.run(tf.global_variables_initializer())

In [12]:
predict.eval(data)  # 초기 예측값

array([[ 0.5       ],
       [ 0.46539634],
       [ 0.53873003],
       [ 0.5041486 ]], dtype=float32)

In [13]:
cost.eval(data)  # 초기 비용

0.69450819

In [14]:
session.run(train_step, data)
predict.eval(data)  # 예측이 변화

array([[ 0.43731436],
       [ 0.40538153],
       [ 0.4731366 ],
       [ 0.44063637]], dtype=float32)

In [15]:
cost.eval(data)  # 비용이 감소한 것을 확인

0.63880473

In [16]:
tl.utils.fit(session, network, train_step, cost, xdata, ydata, x, y,
             batch_size=4,  # 한 번에 4개의 데이터 학습
             n_epoch=1000,  # 최대 1000회까지
             print_freq=100 # 100번 학습마다 비용을 출력
             )
predict.eval(data)  # 최종 예측

Start training the network ...
Epoch 1 of 1000 took 0.015011s, loss 0.638805
Epoch 100 of 1000 took 0.001001s, loss 0.142582
Epoch 200 of 1000 took 0.000000s, loss 0.081254
Epoch 300 of 1000 took 0.001000s, loss 0.056328
Epoch 400 of 1000 took 0.000000s, loss 0.042923
Epoch 500 of 1000 took 0.000000s, loss 0.034595
Epoch 600 of 1000 took 0.000500s, loss 0.028936
Epoch 700 of 1000 took 0.001001s, loss 0.024848
Epoch 800 of 1000 took 0.000500s, loss 0.021761
Epoch 900 of 1000 took 0.001001s, loss 0.019349
Epoch 1000 of 1000 took 0.000500s, loss 0.017413
Total training time: 0.578486s


array([[  1.24064190e-05],
       [  2.02165637e-02],
       [  2.02165730e-02],
       [  9.71684635e-01]], dtype=float32)

In [17]:
numpy.set_printoptions(suppress=True)  # 수치를 일반적인 형태로 표시하게 설정
predict.eval(data)  # 최종 예측 다시 출력

array([[ 0.00001241],
       [ 0.02021656],
       [ 0.02021657],
       [ 0.97168463]], dtype=float32)

In [18]:
session.close()