# Tensor Manipulation

In [1]:
import tensorflow as tf
import numpy as np
import pprint

In [2]:
tf.set_random_seed(888)

In [3]:
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

### n-D Array

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
tf.shape(t).eval()

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


array([4, 3])

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [6]:
t = tf.constant([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
tf.shape(t).eval()

array([2, 3, 4])

### Watch out broadcasting

In [7]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

In [8]:
# Matmul 
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [9]:
# multiply
(matrix1*matrix2).eval()

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

### Random values for variable initializations

In [10]:
tf.random_normal([3])

<tf.Tensor 'random_normal:0' shape=(3,) dtype=float32>

In [11]:
tf.random_normal([3]).eval()

array([-0.94555169,  1.09028363, -0.7708953 ], dtype=float32)

In [12]:
tf.random_uniform([3]).eval()

array([ 0.73266792,  0.93271077,  0.84417903], dtype=float32)

In [13]:
tf.random_uniform([2, 3]).eval()

array([[ 0.60033214,  0.7229501 ,  0.26960909],
       [ 0.18909931,  0.23465931,  0.16058278]], dtype=float32)

### Reduce Mean/Sum

In [14]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [15]:
x = [[1., 2.],
     [3., 4.]]

In [16]:
tf.reduce_mean(x).eval()

2.5

In [17]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [18]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [19]:
tf.reduce_sum(x).eval()

10.0

In [20]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [21]:
tf.reduce_sum(x, axis=1).eval()

array([ 3.,  7.], dtype=float32)

In [22]:
tf.reduce_mean(tf.reduce_sum(x, axis=1)).eval()

5.0

### Argmax with axis

In [23]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [24]:
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [25]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

### Reshape, squeeze, expand_dims

In [26]:
t = np.array([[[0, 1, 2], [3, 4, 5]],              
              [[6, 7, 8], [9, 10, 11]]])

In [27]:
t.shape

(2, 2, 3)

In [28]:
tf.reshape(t, shape=[-1, 3]).eval() # 한 차원을 줄인다.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [30]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

### One hot

In [31]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [32]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)  # one_hot을 하면 차원이 늘어나므로 줄여준다.
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

### Stack

In [33]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

In [34]:
tf.stack([x, y, z]).eval()   # Pack along first dim.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

### Ones like and Zeros like

In [36]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [37]:
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

###  Zip

In [39]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [40]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
