In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.30619437 0.85759201 0.55136595 0.74495219 0.73044688]
 [0.1937065  0.08545442 0.91938861 0.32690858 0.61555914]
 [0.18842079 0.67194898 0.69866691 0.30269387 0.25555033]]


#### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x, y)

array([[ 0.30619437,  1.85759201,  2.55136595,  3.74495219,  4.73044688],
       [ 5.1937065 ,  6.08545442,  7.91938861,  8.32690858,  9.61555914],
       [10.18842079, 11.67194898, 12.69866691, 13.30269387, 14.25555033]])

In [4]:
np.divide(x, y)

array([[ 0.        ,  1.16605564,  3.62735494,  4.02710405,  5.47609977],
       [25.81224662, 70.21286695,  7.61375545, 24.47167327, 14.62085361],
       [53.07270095, 16.37029059, 17.17556657, 42.94768119, 54.78372944]])

In [5]:
x + y

array([[ 0.30619437,  1.85759201,  2.55136595,  3.74495219,  4.73044688],
       [ 5.1937065 ,  6.08545442,  7.91938861,  8.32690858,  9.61555914],
       [10.18842079, 11.67194898, 12.69866691, 13.30269387, 14.25555033]])

In [6]:
x / y

array([[ 0.        ,  1.16605564,  3.62735494,  4.02710405,  5.47609977],
       [25.81224662, 70.21286695,  7.61375545, 24.47167327, 14.62085361],
       [53.07270095, 16.37029059, 17.17556657, 42.94768119, 54.78372944]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [7]:
print(y)

[[0.30619437 0.85759201 0.55136595 0.74495219 0.73044688]
 [0.1937065  0.08545442 0.91938861 0.32690858 0.61555914]
 [0.18842079 0.67194898 0.69866691 0.30269387 0.25555033]]


In [8]:
np.mean(y)

0.49658996810061823

In [9]:
y.mean()

0.49658996810061823

In [10]:
np.max(y)

0.9193886053175591

In [11]:
np.argmax(y)  # index return

7

In [12]:
np.var(y), np.median(y), np.std(y)

(0.06871140620497941, 0.5513659490147023, 0.262128606231711)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [13]:
y

array([[0.30619437, 0.85759201, 0.55136595, 0.74495219, 0.73044688],
       [0.1937065 , 0.08545442, 0.91938861, 0.32690858, 0.61555914],
       [0.18842079, 0.67194898, 0.69866691, 0.30269387, 0.25555033]])

In [14]:
np.sum(y, axis=None)

7.448849521509273

In [15]:
np.cumsum(y)

array([0.30619437, 1.16378638, 1.71515233, 2.46010452, 3.1905514 ,
       3.38425791, 3.46971233, 4.38910093, 4.71600951, 5.33156865,
       5.51998944, 6.19193841, 6.89060532, 7.19329919, 7.44884952])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [16]:
z = np.random.randn(10)
print(z)

[-0.79569546 -0.56549305  1.18266684  2.29646211  0.29316201  0.57796109
 -0.57605615  0.64174618 -0.37937346  0.44459962]


In [17]:
z > 0

array([False, False,  True,  True,  True,  True, False,  True, False,
        True])

In [18]:
np.any(z > 0)

True

In [19]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [20]:
z = np.random.randn(10)
print(z)

[ 1.05606736  2.56124411 -0.30088723 -0.0523781   1.07670099 -0.77391907
 -1.22358159  0.83063577  0.81160901  0.37403284]


In [21]:
np.where(z > 0, z, 0)

array([1.05606736, 2.56124411, 0.        , 0.        , 1.07670099,
       0.        , 0.        , 0.83063577, 0.81160901, 0.37403284])