In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3, 3)
print(x)

[[0.372371   0.70303091 0.57284341]
 [0.9109576  0.04888479 0.02717197]
 [0.22722146 0.24901624 0.81371673]]


In [3]:
np.matmul(x, np.linalg.inv(x))


array([[ 1.00000000e+00,  6.39562122e-17,  9.87585187e-17],
       [ 7.73011705e-19,  1.00000000e+00, -7.59891882e-18],
       [ 9.17232922e-19,  5.59636275e-17,  1.00000000e+00]])

In [4]:
x @ np.linalg.inv(x)

array([[ 1.00000000e+00,  6.39562122e-17,  9.87585187e-17],
       [ 7.73011705e-19,  1.00000000e+00, -7.59891882e-18],
       [ 9.17232922e-19,  5.59636275e-17,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍학의 합 : 25. 호랑이 다리와 홍학 다리의 합은 64
   - x + y = 25
   - 4x + 2y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 4 & 2 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [5]:
A = np.array([[1, 1], [4, 2]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[ 7. 18.]


True